### ISSUE TITLE
 from utils.xtb import * cannot Find the path 

### ISSUE THREAD

**Issue by MachineGUN001** [gcorso/torsional-diffusion#17]
Traceback (most recent call last):
  File "e:\Cheminfo_Workshop\5_Docking_Lab\torsional-diffusion-master\generate_confs.py", line 11, in <module>
    from diffusion.sampling import *
  File "e:\Cheminfo_Workshop\5_Docking_Lab\torsional-diffusion-master\diffusion\sampling.py", line 4, in <module>
    from diffusion.likelihood import *
  File "e:\Cheminfo_Workshop\5_Docking_Lab\torsional-diffusion-master\diffusion\likelihood.py", line 7, in <module>
    from utils.xtb import *
  File "e:\Cheminfo_Workshop\5_Docking_Lab\torsional-diffusion-master\utils\xtb.py", line 12, in <module>
    os.mkdir(my_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/8508'

while I try to set the temp file, 
how can I change the temp file. many thanks,

best,
Sh-Y

**Comment by lorryzzl** [comment]
You can try os.makedirs() instead.

**Comment by MachineGUN001** [comment]
> You can try os.makedirs() instead.

that works. thanks a lot!
